language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
sudo: false
cache: pip

install: pip install .

script: cd example; bash bootstrap.sh test; cd ..

notifications:
    slack: wong-students:0G5vqABleFmfpzOiWkIPlc3j#travis
    email: false
